params:
  ElasticNet:
    alpha: 0.2
    l1_ratio: 0.1
    random_state: 42

  RandomForest:
    n_estimators: 200
    max_depth: 10
    min_samples_split: 2
    random_state: 42

  XGBoost:
    n_estimators: 300
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    random_state: 42